spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/records?useUnicode=yes&characterEncoding=UTF-8
    username: root
    password: jiayan1234
mybatis:
  type-aliases-package: com.example.demo.dao
  mapper-locations: classpath:mapper/*Mapper.xml



